# Reference: https://docs.gitbook.com/integrations/github
# Root directory to locate the content
# Default is the root directory of the repository.
root: ./gitbook
​
# Files to use as SUMMARY/README.
# (Relative to <root> directory)
structure:
  readme: README.md
  summary: SUMMARY.md